### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by schizobulia** [Qinmei/qinvideo#102]
操作系统：ubuntu
Node： v12.0.0

前端npm start 之后显示 substr 为 undefined，

具体代码是在 public\web\utils\util.js 文件中
```javascript
export const hexToRgb = (hex, opacity) => {
  const rgb = [];

  hex = hex.substr(1);  //此处传递进来的可能是undefined，导致前端无法正常显示

  if (hex.length === 3) {
    hex = hex.replace(/(.)/g, "$1$1");
  }

  hex.replace(/../g, function(color) {
    rgb.push(parseInt(color, 0x10));
  });

  return `rgba(${rgb.join(",")},${opacity})`;
};
```

**Comment by Qinmei** [comment]
好，我周末看看；

这个估计是某个第三方库升级了导致的错误， 可以先用yarn试试

**Comment by schizobulia** [comment]
使用yarn 也不行 ，我给了hex一个默认值。

而且静态资源好像失效了，运行之后public下的资源都是404

**Comment by schizobulia** [comment]
我好像知道怎么回事了，您这边是默认把egg-static给屏蔽了，只能是使用一个静态资源服务器去访问public目录才可以。

我看了您的视频部署教程，使用宝塔固然方便，但过于和宝塔耦合是不是不太好(个人想法)，是不是应该先保证Egg.js和Next.js原生部署方法会好一点。

如果可以的话，感觉整体部署脱离宝塔会不会好一点,。
后端项目与前端项目分离开会好一点。

**Comment by Qinmei** [comment]
我们不会使用egg-static，因为它性能比不上nginx,  所以静态资源以及反代这块只需要nginx即可，当然如果你不想用nginx，可以用apache，这个也行

宝塔就是方便使用的，如果你不使用面板，手动装一个nginx就行

目前就是前后端分离的模式， 但是前端访问后端的接口以及上传图片这些都没有做到完全独立，所以将前后端部署在一起，除非你的图片全是OSS，否则你依旧要在后台开一个静态资源服务器

之所以这么搞，主要还是降低新手的门槛，能够比较方便的起一套服务，如果有能力的话可以自己修改，目前耦合的无非就是配置文件以及静态资源了

**Comment by schizobulia** [comment]
其实我想说的是：把/public/web/  这个项目放在这个位置有点别扭，而且如果分离的话，是不是把public目录独立于后端接口的项目  整体目录结构会更加清晰一些

此外个人感觉docker可能是比宝塔是更好的选择

目录分配：
- qinVideo
   - api
   - public
   - web

[这个我修改之后的目录结构](https://github.com/schizobulia/qinVideo/tree/sc-dev)

当然这是我的个人建议:smile:

**Comment by Qinmei** [comment]
因为后台需要写入一些配置文件, 所以public文件夹要在api的里面, 避免获取更高级别的权限导致的一些安全问题

docker门槛有点高, 虽然更合适, 暂时不考虑

**Comment by schizobulia** [comment]
写入配置文件的话，可以考虑使用shell会更优一点。

该Issue给hex一个默认值即可解决。
感谢回复@Qinmei
