### ISSUE TITLE
希望添加视频直链防盗链的功能

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#105]
希望可以在后台添加视频直链防盗链的功能，不单单只是用Nginx验证referer是否正确。可以在播放url添加一些什么参数的办法。这个我不太懂，不知道表述的是否清楚。

**Comment by Qinmei** [comment]
现在就有啊，nginx secure link, 这个是通过密钥以及时间的双重校验的去做的，每次播放的时候后台会根据你的密钥以及有效时间去生成参数，然后带在url上，nginx设置好之后每次请求时会自动校验这两个参数是否准确， 不正确就会返回错误， 具体的可以看文档的播放设置那块

**Comment by Tridagger** [comment]
竟然已经有这个功能了，我去看看！
