### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by HarryZhou7** [Qinmei/qinvideo#109]
请问移动端的程序目录需要指向哪个文件？谢谢

**Comment by Qinmei** [comment]
https://qinvideo.org/docs/deploy/install#3-%E5%AE%89%E8%A3%85-nginx

照着上面这里实践即可

**Comment by HarryZhou7** [comment]
上面是这样写的，然后创建 移动端 静态网站, 网站的程序目录需要指向上面后台文件目录 的 public 文件夹; 我不知道哪个是后台文件目录，请说明。谢谢

**Comment by HarryZhou7** [comment]
是app文件夹吗？

**Comment by Qinmei** [comment]
public文件夹
