### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by gxggpn** [Qinmei/qinvideo#11]
后台-设置-图片设置
设置图片后刷新还是没上传成功！还有管理员不能修改密码的么？

**Comment by Qinmei** [comment]
图片上传不成功看下文件夹权限的配置, uploads跟public的img要有读写权限

**Comment by Qinmei** [comment]
管理员不能直接修改密码, 你要实在想改, 进数据库直接改就是了, 不过密码进行过MD5转换, 先自己创建个账号设置下密码然后复制粘贴过去就行
