### ISSUE TITLE
搭建问题

### ISSUE THREAD

**Issue by zhulilia** [Qinmei/qinvideo#111]
这个程序对于小白搭建起来挺困难 出现了作者大大视频教程里面没有出现的错误 属实很难受啊

**Comment by Qinmei** [comment]
有什么问题直接在这提即可，看到就会回复

**Comment by zhulilia** [comment]
> 有什么问题直接在这提随，看到就会回复
老哥我加了那个Q群 能不能同意一下

**Comment by zhulilia** [comment]
> 有什么问题直接在这提随，看到就会回复

![QQ截图20210226150854](https://user-images.githubusercontent.com/52519793/109267520-a5d15200-7844-11eb-9253-d583714ccacb.png)

**Comment by zhulilia** [comment]
> 有什么问题直接在这提随，看到就会回复

这个咋整老哥

**Comment by Qinmei** [comment]
后台启动错误

**Comment by zhulilia** [comment]
> 后台启动错误

咋解决

**Comment by zhulilia** [comment]
> 后台启动错误

怎么解决呢
