### ISSUE TITLE
希望登录的用户名可以改成邮箱

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#114]
希望登录的用户名可以改成邮箱，因为用户名可以是中文，导致很多用户登录时会忘记自己的用户名是什么了。一般的网站登录的用户名都是英文+数字的，或者是邮箱登录。这样不容易忘记。

同时想问问大大新版本的进度如何了，希望在新版本中能够换一个文本编辑器，起码能编辑些简单样式，现在这个编辑器缩进都不好用。新版本什么时候会出demo可以体验一下呢？

**Comment by Qinmei** [comment]
第一点倒是很好修改，这个倒没啥，支持用户名以及邮箱双重验证就行

新版本的话进度比较慢，目前工作比较忙，不像之前那么悠闲，所以一般只能在周末开发，稍微有点事情基本上就没啥进度了

最主要的原因还是在于，新版本的调整预计会很大，我个人设想的是，后台前端等等全新调整，目前的2.x版本只能说可以用于个人小站点，无法用于实际生产的，比如说不支持docker部署，无法走构建的流水线，新增机器资源的自由调度等等

虽然对于个人来用好像没啥区别，但这也是我一直思考的一个点，那就是个人站点离企业级相差的太远了，当我们还在使用php这种源码站点的时候，企业早就已经上了各种微服务，什么云原生各种概念，这样就会导致个人站点只能小打小闹，毕竟你从基础上就落后一大截

所以现在也是在思考如何能够将一些企业的东西尽量搬到开源项目上来，这样项目也不至于有太多的先天不足，才能保证项目具有长久的活力，毕竟也没人想去维护一套过时老旧的系统

总结：
1. 目前技术选型以及底层的调整都还没有彻底完成，另外现在规划的就是全新的3.0版本，目前的2.x版本只要没啥大BUG，基本上就不会更新了
2. 3.0的开发工作目前进度只能说是10%，有很多想法想要去尝试，但是一时半会也很难有演示出来
