### ISSUE TITLE
希望支持采集插件

### ISSUE THREAD

**Issue by ghost** [Qinmei/qinvideo#115]
希望对接下苹果cms的采集接口，可以运行插件(*╹▽╹*)

**Comment by Qinmei** [comment]
现在就支持啊，云端那块添加苹果CMS的地址就行

**Comment by ghost** [comment]
> 现在就支持啊，云端那块添加苹果CMS的地址就行

要不是老兄在我的仓库下面留言，我还真不知道老兄这个项目

**Comment by ghost** [comment]
https://github.com/Tridagger 这位老兄，好像你们一起做的项目。他在我那留了个言，我才发现这个项目的。很牛

**Comment by Tridagger** [comment]
> https://github.com/Tridagger 这位老兄，好像你们一起做的项目。他在我那留了个言，我才发现这个项目的。很牛

没有没有，我也是这个项目的收益者，主要弄英语配音的动画，这种配音的视频很需要字幕，正好作者支持了。

**Comment by ghost** [comment]
> 现在就支持啊，云端那块添加苹果CMS的地址就行



> > https://github.com/Tridagger 这位老兄，好像你们一起做的项目。他在我那留了个言，我才发现这个项目的。很牛
> 
> 没有没有，我也是这个项目的收益者，主要弄英语配音的动画，这种配音的视频很需要字幕，正好作者支持了。

很不错的项目，我本来想和作者交流下redis缓存方面的思路。加不进去群，加作者qq也是【加不了】

**Comment by Qinmei** [comment]
最近都没上QQ，工作比较忙，直接在GitHub交流就行呗
