### ISSUE TITLE
关于3.0问题

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#117]
3.0是否支持用户迁移，还是说用户需要重新注册

**Comment by Qinmei** [comment]
用户迁移应该是没啥问题的，但是估计只能保存用户的账户信息，收藏那些就不好说了，不过目前还在初期设计阶段，也不好说死

**Comment by 183452584** [comment]
2.0的后台链接咋修改?我想自定义以免被别人登录，

**Comment by Qinmei** [comment]
后台链接暂时无法修改，因为直接部署到了二级目录里，需要前后端的同时配置，暂时无法实现

**Comment by 183452584** [comment]
希望3.0能自定义后台链接
