### ISSUE TITLE
请问前台的页面能不能修改

### ISSUE THREAD

**Issue by xzyone** [Qinmei/qinvideo#12]
我想用大佬的程序做个视频站，不限于是番剧也有可能是国内电视剧之类的，所以程序前台后台都定义为番剧有点局限，我看文档前台是封装好的，那模板的文字还能不能修改呢

**Comment by Qinmei** [comment]
暂时改不了, 这些都是自动生成的文件, 或者你可以试试能不能找到那几个字符串进行替换
