### ISSUE TITLE
请问2.0版本实现番剧评分的功能了吗？

### ISSUE THREAD

**Issue by limeng4835652** [Qinmei/qinvideo#15]
请问2.0版本实现番剧评分的功能了吗？感觉这个功能还是蛮重要的！

**Comment by Qinmei** [comment]
番剧评分这个怎么说呢, 一旦实现用户打分, 那么你就不能引用其他站点的分数, 所有的番剧初始分数都是为空的, 对于一些小站点而言, 其实很没必要, 目前也是在考虑怎么弄合适点

**Comment by limeng4835652** [comment]
> 番剧评分这个怎么说呢, 一旦实现用户打分, 那么你就不能引用其他站点的分数, 所有的番剧初始分数都是为空的, 对于一些小站点而言, 其实很没必要, 目前也是在考虑怎么弄合适点

我想弄一个英配动画的网站，因为配音是英语的，所以配音和分数有直接关系，不能直接用其他站点的分数。这是我现在弄的小网站：www.edatribe.com  想用大大的框架做一个能在线播放的，字幕可以中英文切换的网站。我是小白一个，所以在代码方面帮不了太多忙，只能提一些小小的建议。见谅了！

**Comment by limeng4835652** [comment]
我也一直在关注2.0版本的进度呢，希望可以早一点体验到新版本。我也加QQ群了，发现群里很少讨论qinmei。所以在这里和你交流一下。

**Comment by Qinmei** [comment]
群里面以吹水为主, 技术方面还是直接在github上交流好一点;

评分系统因为要考虑到性能以及数据库设计, 所以这个会在后期评估下, 目前主要是将2.0尽快重构出来, 如果确认性能不会有太大的影响, 那么后期会加上;

目前2.0的进度则是整体功能已经完成一大半, 正在对接后台管理面板, 字幕以及清晰度切换也都在计划范围之内

**Comment by Qinmei** [comment]
有任何建议的话也可以在此提出, 评估可行之后也会加上去
