### ISSUE TITLE
后台设置标题报错

### ISSUE THREAD

**Issue by J1anCan** [Qinmei/qinVideo#17]
后台设置一栏中设置网站名提交报错
Config validation failed: aboutus: Cast to String failed for value "[]" at path "aboutus"
请问是数据类型错了吗，要怎么解决？

**Comment by J1anCan** [comment]
是不是版本的问题？

**Comment by Qinmei** [comment]
关于我们 一栏需要填写, 默认的数据格式不对

**Comment by J1anCan** [comment]
已解决，感谢
弱弱问一句，大佬是没怎么上Q吗，想加一下，好友申请还没通过orz

**Comment by Qinmei** [comment]
bug已解决, 更新即可, 另外不加Q, 需求问题直接GitHub发issue
