### ISSUE TITLE
关于前台模板的设计

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinVideo#20]
提一个小小的建议：
在设计前台模板时可以参考一下Funimation，Netflix，Hulu ，HIDIVE，（需要翻墙）这些网站的设计。
感觉国内的动漫站的样式大多都千篇一律。国外这些动漫网站的设计感觉很高大上，很吸引人。

![QQ截图20191214235256](https://user-images.githubusercontent.com/9511835/70851292-40f33b80-1ece-11ea-810a-858672a49392.png)
![QQ截图20191214235608](https://user-images.githubusercontent.com/9511835/70851293-418bd200-1ece-11ea-8820-1b6c1923e5b4.png)
![QQ截图20191214235737](https://user-images.githubusercontent.com/9511835/70851294-418bd200-1ece-11ea-938f-54cddd030c25.png)

**Comment by Qinmei** [comment]
设计这块确实是弱项, 因为整个系统做起来的工作量实在是太大, 没空去设计, 不过目前已经根据功能分成了几大块, 好处是可以单独更新, 等后台这些稳定下来没啥问题就可以开撸前端了

**Comment by Tridagger** [comment]
辛苦了，能看出来，这次工作量确实很大！
