### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by Dreamsnyl** [Qinmei/qinvideo#22]
管理员图片正常上传，普通注册用户无法上传图片，控制台显示403

**Comment by Qinmei** [comment]
你这是wordpress的版本?

**Comment by Dreamsnyl** [comment]
完全安装3.0版本的部署

**Comment by Qinmei** [comment]
请在qinPress项目下提issue, 这个基本上就是权限的问题, 普通用户注册后是订阅者的角色, 权限很低, 基本上没有上传图片的权限, 这个需要安装插件, 具体的名称我记不太清楚了, 你可以搜下

**Comment by Dreamsnyl** [comment]
好的，多谢！
