### ISSUE TITLE
创建新动漫报错

### ISSUE THREAD

**Issue by Dreamsnyl** [Qinmei/qinvideo#23]
初始化后，创建出错

Warning: Invalid argument supplied for foreach() in /www/wwwroot/www.api.log8.cn/wp-content/themes/qinpress/qinmei/animate.php on line 7

有分类和类型和对应的别名

**Comment by Qinmei** [comment]
需要创建剧集

**Comment by Dreamsnyl** [comment]
很抱歉没有找到在哪里创建剧集，可能是在新建漫画页面，but新建漫画页面报错，找到报错的源码，应该是循环了一个空数组，（ $eposidecon = get_post_meta( $post->ID, 'baseinfo_episode_con', true );）

**Comment by Qinmei** [comment]
emmm.......时间太久, 这个我也无能为力, 至少我测试过是可以正常创建的, 可能是wordpress更新或者其他的一些问题, 你可以自己尝试修改下
