### ISSUE TITLE
请教v2.0执行yarn start --ignore-stderr后的错误

### ISSUE THREAD

**Issue by ange8506** [Qinmei/qinvideo#24]
请教v2.0执行yarn start --ignore-stderr后的错误
$ egg-scripts start --daemon --title=egg-server-qinvideo-node --ignore-stderr
/bin/sh: egg-scripts: command not found
error Command failed with exit code 127.

**Comment by Qinmei** [comment]
还有很多东西都没集成进去呢, 等年后的正式版吧
