### ISSUE TITLE
安装时没有/public/web 这个文件夹

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#25]
![image](https://user-images.githubusercontent.com/9511835/72805619-4a6e8100-3c8e-11ea-9e3b-37e06e9c4b05.png)
![image](https://user-images.githubusercontent.com/9511835/72805630-535f5280-3c8e-11ea-99ba-f420bd7415ff.png)
![image](https://user-images.githubusercontent.com/9511835/72805655-5ce8ba80-3c8e-11ea-9cc7-ada822f20a58.png)

**Comment by Tridagger** [comment]
![image](https://user-images.githubusercontent.com/9511835/72805801-afc27200-3c8e-11ea-9686-eabd20a0b274.png)
是从这里下载的

**Comment by Qinmei** [comment]
新的镜像我还没打包, 你直接在代码页面下载即可, 或者用这个: https://github.com/Qinmei/qinVideo/archive/2.0.zip

**Comment by Qinmei** [comment]
上面那个release是测试自动部署用的, 忘记更新了
