### ISSUE TITLE
在首页点返回首页的按钮异常

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#26]
点击这个
![image](https://user-images.githubusercontent.com/9511835/72949281-c964d600-3dc2-11ea-8a56-73ed67e8b0d8.png)
显示这个
![image](https://user-images.githubusercontent.com/9511835/72949317-e8fbfe80-3dc2-11ea-8f79-fb9c4d22f896.png)

**Comment by Qinmei** [comment]
首页没有正确启动

**Comment by Qinmei** [comment]
是个BUG啊
