### ISSUE TITLE
播放直链视频存在跨域问题

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#27]
视频链接用的你的安装教程
![image](https://user-images.githubusercontent.com/9511835/72953186-3a11ef80-3dcf-11ea-9771-a94aa03ec235.png)

![image](https://user-images.githubusercontent.com/9511835/72953307-a1c83a80-3dcf-11ea-881b-08f7268dcf10.png)

**Comment by Qinmei** [comment]
.............同源策略好吧, 你找个资源站的视频再来测试
