### ISSUE TITLE
弹幕的问题

### ISSUE THREAD

**Issue by fans2333** [Qinmei/qinvideo#31]
现在是不能存储弹幕了吗  发送的弹幕后台有记录但是所属视频显示已删除

**Comment by Qinmei** [comment]
简单点说，后台存储的弹幕是dplayer的格式，目前无法很好的关联到每个视频，所以有的时候显示已删除并不是视频不存在，而是没关联上，不影响使用，就是后台的显示问题

**Comment by fans2333** [comment]
> 简单点说，后台存储的弹幕是dplayer的格式，目前无法很好的关联到每个视频，所以有的时候显示已删除而不是视频不存在，而是没关联上，不影响使用，就是后台的显示问题

右侧弹幕列表显示正常但在dplayer播放器中所有弹幕都显示undefined

**Comment by Qinmei** [comment]
估计是bug，我有空看看

**Comment by Qinmei** [comment]
已解决
