### ISSUE TITLE
关于生成的主页异常的问题。

### ISSUE THREAD

**Issue by wenzi7777** [Qinmei/qinvideo#33]
### 问题2:页面底部的QQ、邮箱、APP按钮，鼠标悬停时没有出现与演示站相同的效果，请看图片1-4.
<img width="172" alt="2" src="https://user-images.githubusercontent.com/42164227/75136817-d1e16100-5720-11ea-80cb-6c0fda2bb86f.png">
<img width="172" alt="3" src="https://user-images.githubusercontent.com/42164227/75136822-d443bb00-5720-11ea-89bb-c80565bf5a4a.png">
<img width="790" alt="4" src="https://user-images.githubusercontent.com/42164227/75136823-d4dc5180-5720-11ea-9e25-e896f3b59296.png">

<img width="172" alt="1" src="https://user-images.githubusercontent.com/42164227/75136816-d0179d80-5720-11ea-83cc-f6e1346f9756.png">
**我完全参照您的视频及说明文档的安装步骤进行部署网站的。**

**Comment by Qinmei** [comment]
唔, 可以发个网址出来看看, 导航栏应该是因为点击之后需要加载文件导致段时间内页面没有变化. 底部的问题就是样式没有正确的加载, 这个需要具体查看才能看到原因

**Comment by wenzi7777** [comment]
刚刚那个被我删掉了，我重新部署了下网页，网址是http://www.mikufans.info，**我会在下午10点前将这条回复中的网址删掉。**

**Comment by wenzi7777** [comment]
emm，我把下面的工具注释掉了，总之眼不见心不烦的:P
