### ISSUE TITLE
上传漫画，进入文章页报错

### ISSUE THREAD

**Issue by kuaile1993** [Qinmei/qinvideo#34]
![image](https://user-images.githubusercontent.com/52553619/75149219-6f965980-573c-11ea-810c-077e2499ce24.png)

**Comment by kuaile1993** [comment]
![image](https://user-images.githubusercontent.com/52553619/75149717-a02ac300-573d-11ea-800f-eda214ca930c.png)
 演示站的漫画，虽然没有报错，但是也没看到内容

**Comment by kuaile1993** [comment]
抱歉，是我设置的问题

**Comment by kuaile1993** [comment]
抱歉上面是我设置的原因， 我有个和问题想请教下
![image](https://user-images.githubusercontent.com/52553619/75207382-7f04b980-57b3-11ea-89a3-a13786780928.png)  
图片接口和本地图片要怎么设置链接？  特别是图片接口怎么设置？ 要什么样的接口？

**Comment by kuaile1993** [comment]
抱歉上面是设置问题

**Comment by Qinmei** [comment]
漫画这一块测试的比较少, 因为现在也没有漫画采集站可用, 所以这块可能有问题, 你可以多测试下
