### ISSUE TITLE
主页刚开始还可以，上传几部番剧上去就出现了错误。

### ISSUE THREAD

**Issue by wenzi7777** [Qinmei/qinvideo#35]
<img width="272" alt="截屏2020-02-25上午12 34 01" src="https://user-images.githubusercontent.com/42164227/75171562-c749ba80-5766-11ea-9505-d87ac1c612a2.png">
错误如图，请问这是什么原因呢？

**Comment by Qinmei** [comment]
后台管理页面?因为路由直接跳转到了服务端渲染, 没有经过后台, 你尝试下直接访问域名/backend即可, 如果是首页等页面,那就是后台API出了问题

**Comment by wenzi7777** [comment]
不，我是想要进主页，也就是那个小型的node项目运行之后带来的主页，但是刚开始还可以，之后就出现了不可预料的错误（就是前面图中那样），但是其他页面还是可以的，例如我输入域名/animate或者后台还是可以正常进入的。
react的完整错误提示是这个：
**Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**
react限制了更新次数为了防止进入死循环。错误是这个。但是一开始的主页（还可以进的时候的主页）没有这种情况，但是出现了css异常（nav，和footer有异常），因此，是不是这两部分的代码有bug呢？

**Comment by Qinmei** [comment]
唔, 这个还真不好说, 服务端渲染的主页只有两个接口, 理论上不存在什么错误, 你可以打开防火墙, 直接访问:3000这个端口,看看是什么情况

**Comment by wenzi7777** [comment]
嗯。现在直接访问3000端口是css错乱，但是还是没有解决问题。
直接访问3000端口没有问题，不会出现不可预料的错误。但是我访问域名，又是不可预料的错误。（嗯，但是它会先加载页面的一部分再出现不可预料的错误，就是会延迟一段时间，再这段时间里，我发现，轮播图没有加载好。也许问题出现在轮播图上？）

**Comment by Qinmei** [comment]
3000端口是没有加载样式跟js的服务端渲染, 如果能正常显示, 那就是说明后台接口等都没问题, 问题出在代码层面, 这样也不好评估, 你给个地址我看看具体是啥原因

**Comment by wenzi7777** [comment]
嗯，网址是：
http://www.mikufans.info/

**Comment by Qinmei** [comment]
刚刚尝试了下, 在本地跑是完全没问题的, 你尝试下删除_next文件夹然后重新安装试试;

![image.png](https://i.loli.net/2020/02/27/WD3n9SBMGvO7Fdu.png)

**Comment by wenzi7777** [comment]
太奇怪了，我还是不可以，我删除了_next文件夹，我如果进入网站的话，它会先加载一会儿，然后再变成错误，大概是这样子：
<img width="1436" alt="截屏2020-02-27下午2 33 10" src="https://user-images.githubusercontent.com/42164227/75418655-f763aa00-596e-11ea-8747-ce7ff33e8d61.png">
<img width="1436" alt="截屏2020-02-27下午2 37 27" src="https://user-images.githubusercontent.com/42164227/75418659-faf73100-596e-11ea-9957-b6163d5bd010.png">

**Comment by wenzi7777** [comment]
好像现在访问其他页面也出问题了，，访问域名/post会无限刷新，访问域名/animate会白屏。

**Comment by wenzi7777** [comment]
额，我运行npm stop之后，然后npm start就跑不起来项目了，加了--ignore-stderr也没用。。
emm，我放弃了。😂
