### ISSUE TITLE
关于Qinvideo的一些建议

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#36]
感谢大佬的项目，目前已经使用qinvideo已经10天左右了，运行很稳定。这是我的网址  https://v.edatribe.com 
服务器是香港阿里云轻量应用服务器，1核1G。网站主要用来英配动画的在线播放，并且带有软字幕。
下面说一下我的建议：

关于软字幕建议
1. 目前字幕的颜色是白色无边框和阴影，如果播放视频是白色背景时会出现看不清字幕的情况。
（我感觉可以修改DPlayer/src/css/subtitle.scss 里的参数）
2. 字幕的位置有些靠上，应该再下移一些。
3 字幕字体的大小不能随着播放器的大小而变化。全屏后会造成字幕过小。

关于注册用户头像的建议
建议添加QQ头像的功能，因为有些用户注册时上传的图片体积过大，有的头像会达到几M，感觉有些浪费服务器资源。在注册时可以添加QQ号信息，然后根据 https://q1.qlogo.cn/g?b=qq&nk=945794520&s=100 这样的链接引用QQ头像作为用户头像。

关于文本编辑器的建议
1. 引用图片时不能控制图片的大小，好像是无论尺寸多大的图片都会铺满。https://v.edatribe.com/post/slug/about  这里二维码是个例子。实际上这个图片尺寸并不大。
2. 编辑器首行不能缩进，无论是用空格还是按TAB键，保存后都失效。https://v.edatribe.com/post/slug/about  这篇文章里也有例子
3. 如果编辑器支持Markdown语法就更好了

关于百度统计的建议
我试了填写几次链接都检测不到。
这是我的百度统计代码

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?211b10aa080375219ec5754c77e43aea";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

我尝试过，
https://hm.baidu.com/hm.js?211b10aa080375219ec5754c77e43aea
"https://hm.baidu.com/hm.js?211b10aa080375219ec5754c77e43aea"
hm.src = "https://hm.baidu.com/hm.js?211b10aa080375219ec5754c77e43aea";
hm.src = "https://hm.baidu.com/hm.js?211b10aa080375219ec5754c77e43aea"
这几种填写方式，都没成功，希望能够在演示站里填写一下，作为参考。

从去年10月一直关注大佬肝代码，真的很佩服，也希望这个项目越做越好。

**Comment by Qinmei** [comment]
感谢支持;

字幕的话目前用的是Dplayer的功能, 实际上我感觉功能很弱, 再加上作者更新的不勤快, 也就没有很好的办法了, 目前正在规划播放器的项目, 希望到时候能够与qinvideo完美结合, 不过这个时间很长, 短时之间恐怕很难有进展;

头像这些图片资源, 想要引用外链其实是很简单的, 只不过都是细枝末节, 等整体完善了之后再考虑细节;如果以后有时间的话, 加上第三方登录也是可行的;

编辑器这个实际上就是markdown编辑器, 只需要按照markdown语法去写就好, 但是这类编辑器最大的问题就是上传图片不太方便. 这个也只能看有没有更好的编辑器出现了;

百度统计这个可能有点问题, 我到时候再看看, 当然你也可以直接把代码添加到index.html里

整个项目涉及到的东西很庞大, 很多依赖都是优秀的开源项目,  我也只能说在产品功能上进行把握, 一旦落实到了细节, 很多都不是我能控制的了, 没有长时间的打磨是不行的, 也希望你在使用的过程中可以提出改进的方向

**Comment by Tridagger** [comment]
谢谢大佬的回答！
