### ISSUE TITLE
请问可以出一个安装更新的视频吗

### ISSUE THREAD

**Issue by fans2333** [Qinmei/qinvideo#37]
不太会操作 更新上有些报错 希望可以出个安装更新的视频教程

**Comment by Qinmei** [comment]
安装的视频是有的:https://qinvideo.org/video/#%E5%AE%89%E8%A3%85, 至于更新, 这个就没必要吧

**Comment by fans2333** [comment]
全部更新是例如在qinvideo2.0的根目录npm stop然后在复制过文件的qinvideo2.0.6的根目录直接npm start吗

**Comment by Qinmei** [comment]
先停止旧的, 然后备份config跟图片到新的文件目录里面, 然后重新跑一遍安装流程, 正常启动了就行, 安装其实很简单, 主要是第一次配置后台很麻烦, 保持数据库不变, 后续每次更新就不用配置了, 启动了就跟之前差不多

**Comment by Tridagger** [comment]
要反复看安装教程，我升级时也遇过类似的问题，后来重启服务器，删掉了_next文件夹，重新执行一遍安装过程就好了！希望对你有帮助。
