### ISSUE TITLE
要求的nginx配置可能因反代出现重定向问题

### ISSUE THREAD

**Issue by kairlec** [Qinmei/qinVideo#4]
使用$host的话如果使用了端口转发会导致丢失端口,为何不使用$http_host
ngnix监听非标准端口如果没有加/,又会导致nginx返回的Location又不带端口号导致重定向地址错误
根添加规则,添加一句判断
```
if (-d $request_filename) {
    rewrite [^/]$ $scheme://$http_host$uri/ permanent;
}
```

**Comment by qinvz** [comment]
nginx代理这个我没有经过严格的验证,  有时间我再参考看看
