### ISSUE TITLE
默认图片不显示

### ISSUE THREAD

**Issue by jiuyu1139** [Qinmei/qinvideo#44]
问题：
  设置--》图片设置--》默认头像和默认背景图不显示

**Comment by Qinmei** [comment]
你这个指的是啥?是上传了不显示还是设置了之后, 用户面板不显示?

**Comment by jiuyu1139** [comment]
后台设置了默认头像（用户尚未设置头像时的默认展示图）和默认背景图（用户尚未设置专属的背景图时的默认展示图），前端用户中心不显示
