### ISSUE TITLE
采集乱码问题

### ISSUE THREAD

**Issue by haig233** [Qinmei/qinvideo#49]
采集影片后，影片描述会出现乱码
例如：https://moetv.live/animate/slug/av000015
对应的资源站地址是：http://www.okzyw.com/?m=vod-detail-id-1011.html

**Comment by Qinmei** [comment]
有空加上采集信息的转换

**Comment by Qinmei** [comment]
出现概率很低, 几千部大概有七八部有问题吧, 这个纯粹是源网站排版不规范的原因, 懒得做兼容了, 很麻烦
