### ISSUE TITLE
能不能在视频添加那里可以像苹果cms导入视频数据

### ISSUE THREAD

**Issue by qazwse4541** [Qinmei/qinvideo#5]
个人手动添加太累了

**Comment by qazwse4541** [comment]
就是调用其他资源采集站的api接口

**Comment by Qinmei** [comment]
不能, 有需要可以自己写

**Comment by Qinmei** [comment]
另外高级版有提供一些设定好的数据导入功能, 如果不想使用高级版可以自己研究接口然后导入数据

**Comment by qazwse4541** [comment]
高级版key没有啊！

**Comment by qazwse4541** [comment]
感觉后台可以把前台的项目地址弄到后台来。

**Comment by qazwse4541** [comment]
就是这个链接：https://demo.qinvideo.org/web/qinvideo.org

**Comment by Qinmei** [comment]
前台项目本身就是另外单独的， 可以自己写， 后台只提供预置的一套
