### ISSUE TITLE
工具-->字符替换  提示：更新出错, 请检查文件权限等

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#51]
我想批量修改一下视频和字幕的链接，使用字符替换功能，提示：更新出错, 请检查文件权限等。qinvideo的文件夹都给了777权限了。

**Comment by Qinmei** [comment]
将文件夹分配给www用户组, 并将所有的文件夹以及子文件夹的权限设为777

**Comment by Tridagger** [comment]
> 将文件夹分配给www用户组, 并将所有的文件夹以及子文件夹的权限设为777

我试了一下
![image](https://user-images.githubusercontent.com/9511835/76383188-f3d01a00-6395-11ea-932b-f880e7541ccb.png)
然后停止服务，重启服务器，清除浏览器缓存。还是提示：更新出错, 请检查文件权限等。
