### ISSUE TITLE
系列剧集不能按添加顺序排列

### ISSUE THREAD

**Issue by yanxina** [Qinmei/qinvideo#53]
![1](https://user-images.githubusercontent.com/52437415/76725465-40966500-6789-11ea-80b5-dd4bfcb56424.png)

**Comment by yanxina** [comment]
比如多季数的动画，，貌似后台点击专题貌似只能编辑不能排序，，，

**Comment by Qinmei** [comment]
暂时排不了序, 后续再当作优化点吧, 不过第几季顺序是没问题的, 顶多就是剧场版跟OVA这种乱序

**Comment by yanxina** [comment]
> 暂时排不了序，后续再重新优化点吧，不过第几季顺序是没问题的，顶多就是剧场版跟OVA这种乱序

貌似只能排两季超过三季就乱序了，第三季跑到第二季前面了。然后第五季跑到第四季前面了(:3_ヽ)_
![5](https://user-images.githubusercontent.com/52437415/76815934-ebfef280-6839-11ea-9018-016745aa37b2.png)
![1](https://user-images.githubusercontent.com/52437415/76815990-0a64ee00-683a-11ea-88a9-a9f1fa7d577c.png)

**Comment by Qinmei** [comment]
嗯, 后续当做优化点, 这个有点不太好改

**Comment by yanxina** [comment]
> 嗯，后续当做优化点，这个有点不太好改

对了之前用的Typecho的一个影视模板，那个后台是单独添加一个系列，在每个关联的动画里面加入“第一季$文章id，第二季$文章id”之类格式前台就直接显示这样就不会乱序，如图
![1](https://user-images.githubusercontent.com/52437415/76826706-22e40100-6858-11ea-9a62-fe642083ff9d.png)
![2](https://user-images.githubusercontent.com/52437415/76826702-2081a700-6858-11ea-9323-9f9da34de46e.png)
后台专题的话觉得放季度新番合集和活动比较好与系列剧集分开这样？

**Comment by Qinmei** [comment]
如果按照你说的这样去做, 那么每个动画都要关联其他三个, 修改起来会很麻烦, 专题目前的功能还有点弱, 但是设想的是直接在专题页面就能添加全部的动画, 以后甚至可以将专题提出来, 然后做个活动推荐这种, 这块是需要慢慢打磨的, 现在的先过渡一下吧

**Comment by yanxina** [comment]
> 如果按照你说的这样去做, 那么每个动画都要关联其他三个, 修改起来会很麻烦, 专题目前的功能还有点弱, 但是设想的是直接在专题页面就能添加全部的动画, 以后甚至可以将专题提出来, 然后做个活动推荐这种, 这块是需要慢慢打磨的, 现在的先过渡一下吧

好的感谢大佬辛苦了(￣▽￣)／
