### ISSUE TITLE
移动端不支持登录后台吗？

### ISSUE THREAD

**Issue by uzxz** [Qinmei/qinvideo#55]
是不是移动端不能进后台？

**Comment by uzxz** [comment]
还是说要咋操作😂

**Comment by Qinmei** [comment]
如果你是照着教程来的, 在nginx文件里面有一行是PC端跳转移动端的, 这个自然也包括后台管理, 想要不跳转的话, 在浏览器勾选桌版即可

不过说真的, 移动端没啥必要打开后台, 因为东西太多, 手机端完全放不下, 所以也就没做排版优化, 也就能简单看看数据罢了

**Comment by uzxz** [comment]
哦，谢了
还有就是能不能导入b站上的视频？
轮播怎么加（类型已经加了，不知道怎么把视频上设置为轮播）
我今天刚刚搭建的：v.irils.com
