### ISSUE TITLE
播放问题反馈，4:3的老番播放超框了。

### ISSUE THREAD

**Issue by yanxina** [Qinmei/qinvideo#56]
电脑版
![1](https://user-images.githubusercontent.com/52437415/76922502-da861b00-690b-11ea-9511-ac8653137ccf.png)
手机版
![2](https://user-images.githubusercontent.com/52437415/76922506-de19a200-690b-11ea-93bd-3ba223f63090.png)

**Comment by Qinmei** [comment]
......有点6, 我找个时间修复下
