### ISSUE TITLE
进入 /backend  后台时提示无权限验证不通过

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#58]
![image](https://user-images.githubusercontent.com/9511835/78018077-d3d1bc00-737f-11ea-86c9-57e67eaa8abb.png)
每隔几天进入 /backend  后台时提示无权限验证不通过，清除一下浏览器cookie就能登录了，当天登录都没有问题，不知道这是什么原因。

**Comment by Qinmei** [comment]
token过期了, 后台好像没有清除的机制, 我再看看, 这块当初发现有问题, 后续好像没跟进了

**Comment by Qinmei** [comment]
已经解决，更新即可
