### ISSUE TITLE
弹幕刷新会丢失问题

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#60]
弹幕发送刷新一下就丢失了，没发保存，自己另外做直链解析，如何替换播放器?我后台加链接后，视频信息哪里没看到选择解析那选择。

**Comment by Qinmei** [comment]
列表接口是有缓存的, 默认一小时, 如果感觉用不到, 那就在config.default.ts里面设置成1S, 不过不推荐, 因为请求量一大必然撑不住, 数据库的查询语句目前没有做特殊优化, 只能靠缓存来优化;

至于解析, 简单说下原理, 他是将一个外部的网页嵌进来, 至于里面用的什么播放器长什么样那都是他们的事, 跟本系统无关

**Comment by 183452584** [comment]
关心解析，后台提示说明：当使用解析时, 通过设定正则表达式实现特定解析, 只有在视频处勾选解析才会生效，请问：视频处勾选解析，是不是只要选择播放类型是解析就可以，之前试了没触发外链播放器，还是说要等缓存?

**Comment by Qinmei** [comment]
对, 播放类型选择解析, 然后后台那边设置解析对应的等级以及链接, 就会添加上去, 播放链接是没有加缓存的, 你修改了就会立马生效

**Comment by 183452584** [comment]
请问:正则表达式是填啥

**Comment by 183452584** [comment]
正则表达式是填啥------------------ 原始邮件 ------------------
发件人: "Qinmei"<notifications@github.com>
发送时间: 2020年4月6日(星期一) 中午12:04
收件人: "Qinmei/qinVideo"<qinVideo@noreply.github.com>;
抄送: "183452584"<183452584@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Qinmei/qinVideo] 弹幕刷新会丢失问题 (#60)




 
对, 播放类型选择解析, 然后后台那边设置解析对应的等级以及链接, 就会添加上去, 播放链接是没有加缓存的, 你修改了就会立马生效
 
&mdash;
