### ISSUE TITLE
资源导入显示错误

### ISSUE THREAD

**Issue by haig233** [Qinmei/qinvideo#61]
![Gy0MXq.png](https://s1.ax1x.com/2020/04/06/Gy0MXq.png)
实际上是已经全部导入成功了，但是就是不显示

**Comment by Qinmei** [comment]
先记录下, 有空再仔细验证

**Comment by Qinmei** [comment]
demo站点似乎没出现过这个问题, 你把你的采集网站在demo站跑一下试试
