### ISSUE TITLE
弹幕作者这栏里显示空白

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#64]
弹幕作者这栏里显示空白，评论和评分里显示正常。
![image](https://user-images.githubusercontent.com/9511835/79036775-10ae7600-7bfe-11ea-8f51-349ad93f4289.png)
![image](https://user-images.githubusercontent.com/9511835/79036785-1c9a3800-7bfe-11ea-8b4b-1d8603cd1f85.png)
![image](https://user-images.githubusercontent.com/9511835/79036788-2623a000-7bfe-11ea-8999-2296cc54314c.png)

**Comment by Qinmei** [comment]
想起来了, Dplayer 其实很独立, 他的弹幕功能都是内置的, 外部控制不了什么, 我们就是简单的存储他的弹幕而已, 目前已经拉了一个分支, 后续会把登录验证这些加进去
