### ISSUE TITLE
关于多线路播放组

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#65]
可以添加一个类似苹果那样做一个播放组么，这样也方便不同线路切换，一个链接拼接不太好使，比如一个用世纪互联直链和天翼直接就不一样，拼接的那种完全就没用。

**Comment by Qinmei** [comment]
线路切换你可以用清晰度，每集新增几个不同的来源，用户可以手动切换，但是仅限于直链。

只要你是自己存储资源，不管是天翼云还是onedrive，最后的资源文件夹肯定是一样的，就是前缀不一样而已，你把前缀不一样的部分拿出来放到设置里，这才是拼接的意义，用户全程无感，还可以做到不同等级不同来源。

当然如果想要采集各种资源混搭，那就不支持了

**Comment by 183452584** [comment]
那清晰度在哪弄呢咋没看到
