### ISSUE TITLE
求解答 手贱买卡把账号权限下了 进不去后台怎么提权

### ISSUE THREAD

**Issue by 1479492410** [Qinmei/qinvideo#66]
后台提示无权限验证不通过 看文档发现100是管理员

**Comment by Qinmei** [comment]
进数据库处理, 另外把所有用户都删了就会重新生成一个默认账号

**Comment by 1479492410** [comment]
> 进数据库处理，另外把所有用户都删除了就会重新生成一个替代账号

谢谢大大 删除用户可以解决
