### ISSUE TITLE
疑似是添加动漫导致主页进不去

### ISSUE THREAD

**Issue by 1479492410** [Qinmei/qinvideo#67]
![image](https://user-images.githubusercontent.com/48371323/81048497-0a56a580-8eef-11ea-904e-cc4820498ebb.png)
![image](https://user-images.githubusercontent.com/48371323/81048533-17739480-8eef-11ea-98e2-5b137cdbcd8c.png)
![image](https://user-images.githubusercontent.com/48371323/81048563-22c6c000-8eef-11ea-9fd4-278e5169c9e2.png)
后台审核通过后就这样子了 也可以正常搜索观看之类的但是主页进不去分类全部消失
目前使用的域名ipv6.tk

**Comment by 1479492410** [comment]
观察了一下 大概是欧洲服务器的原因？还是没有进行服务器渲染导致的这种现象

**Comment by Qinmei** [comment]
先设置然后保存, 你这是没有生成配置文件导致的

**Comment by 1479492410** [comment]
> 先设置然后保存，你这是没有生成配置文件导致的
谢谢 可以了
想问一下大大会放出来安卓app端吗？

**Comment by Qinmei** [comment]
后续再看吧，而且说实话，就算放出来也很难搞定，涉及到的东西太多

**Comment by 1479492410** [comment]
好的 谢谢大大
