### ISSUE TITLE
关于用户注册的BUG

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#69]
1. 新用户注册后，在面板中今日注册量无显示，始终是0。
2. 新用户注册成功后，没有提示，会误导用户再次注册，再次注册后显示用户名或邮箱已占用，导致注册注册其他账号。希望增加注册成功的提示。

ver. v2.1.0

**Comment by Qinmei** [comment]
注册成功的提示很早之前就修复了啊，这个是2.1.0的问题？

**Comment by Tridagger** [comment]
不知道演示站是否是最新的版本，我测试了一下，也是有无提示这个bug。

**Comment by Qinmei** [comment]
看了下, 合并版本的时候有部分文件遗漏没有合并上去, 这周末我再详细检查下吧
