### ISSUE TITLE
[Bug]  在域名/animate/ 下点击某分类下的查看更多，跳转进去显示的是所有动画，而不是这个分类的动画

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#71]
例如，
![image](https://user-images.githubusercontent.com/9511835/81887718-5a5df800-95d2-11ea-861d-484864a89be1.png)
英配剧场分类下有7个动画，点击查看更多后，把其他动画也显示出来了。
![image](https://user-images.githubusercontent.com/9511835/81887843-9b560c80-95d2-11ea-8d8a-ef4043173275.png)

**Comment by Qinmei** [comment]
确实有问题， 两个版本之间的冲突有点大
