### ISSUE TITLE
请问配置文件中邮件验证链接应该怎么填呢？

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#73]
authUrl: 'https://m.qinmei.video/auth/verify', // 邮件验证账户的地址

这里我修改成我的域名，但点开邮件中收到的地址，却直接跳转到网站主页了。

![image](https://user-images.githubusercontent.com/9511835/82139282-4bd54200-9859-11ea-841f-e89ac304b6e1.png)

**Comment by Qinmei** [comment]
这个是是用来做邮件验证的，因为你可能做了移动端与主页的相互跳转， 所以在pc端打开就会自动跳转到主页

可以将移动端跳转到首页的代码去掉， 这样就只会打开移动端的验证， 不过这块逻辑还可以再优化下， 反正只要你不开邮件验证就不用填
