### ISSUE TITLE
动画信息的编辑里，下载信息和下载链接不能存空值

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#74]
![image](https://user-images.githubusercontent.com/9511835/82140081-c86b1f00-985f-11ea-8ff2-48d7d77a7b76.png)
我不想放置下载链接，将信息删除后，保存，再进去原信息仍然存在，但可以修改信息，保存后信息发生了变化。

**Comment by Qinmei** [comment]
可能是个BUG
