### ISSUE TITLE
关于邮件认证问题

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#77]
使用邮件认证会跳转你的网站无法验证，另外待删除等于封号，请问能否限制一下待删除用户?
![Screenshot_2020-05-29-19-50-30-367_com tencent mobileqq](https://user-images.githubusercontent.com/47927966/83257524-25af8a80-a1e7-11ea-98a1-401106670ba8.jpg)

**Comment by 183452584** [comment]
还有一个问题评论审核会保存
![IMG_20200529_202924](https://user-images.githubusercontent.com/47927966/83259703-1a5e5e00-a1eb-11ea-8ff2-9c1335984ae2.jpg)

**Comment by Qinmei** [comment]
https://github.com/Qinmei/qinVideo/blob/0c48cccfbf410096523a059f72ca6cd1ff8e674d/config/config.default.ts#L59

验证地址自己改, 待删除用户还要怎么改?

**Comment by Qinmei** [comment]
另外, 这是评论编辑, 你内容为空, 自然不能提交

**Comment by 183452584** [comment]
另外你弹幕审核和评论开关打开了，没单独进行审核按钮么，如果没有那么开发那个没任何意义，如果没一个要回复审核，不太好吧。
待删除，不是等于封号那样么，不应该限制一下么?那么它和其他验证用户没啥区别啊。

**Comment by Qinmei** [comment]
待删除用户禁止评论发送弹幕, 这已经够了, 那不然还要限制用户观看不成, 他直接推出去不就得了

审核是要你用编辑去修改, 而不是回复, 回复是快捷评论

**Comment by 183452584** [comment]
待删除有限制就行，
另外弹幕审核我看了一下并木有编辑按钮啊，另外评论那个我编辑通过了发现还是审核状态，然后去你演示站看了一下把通过改一下审核，还是通过状态不知道是不是bug

**Comment by Qinmei** [comment]
没加上去

**Comment by Qinmei** [comment]
先别关, 等我修复了会关的

**Comment by 183452584** [comment]
哦好的，我以为不是bug，我就关了
