### ISSUE TITLE
重点!请注意 重点问题

### ISSUE THREAD

**Issue by tokenlike** [Qinmei/qinvideo#79]
能否为每个页面提供专属的关键词和描述

<title></title>
 <meta name="keywords" content="               " />
<meta name="description" content="" />

作为一个站长 最希望的就是能够被搜索引擎收录并且来访蜘蛛,如果没有关键词和描述 蜘蛛所爬取的内容会很分散 甚至是不爬取！
我本来是自己修改页面关键词 但是发现 修改了视频页关键词 导致所有的pc页面关键词都是一致的！

**Comment by Qinmei** [comment]
这就是spa，基本无seo，当然谷歌其实早就能爬了，百度肯定是不行的，想要seo，那就只能专门开发服务端渲染的主题，很遗憾我对这个没兴趣，不考虑做这块的东西
