### ISSUE TITLE
服务器负载很低但前台的连接非常慢

### ISSUE THREAD

**Issue by ange8506** [Qinmei/qinvideo#8]
后台的速度很正常，前台加载却需要很久。大概会是哪里的问题呢。。
配置文件加入以下两行会出错但是错误提示是从需要加入的第一条client_max_body_size开始提示。
location =/ {
    if ($http_user_agent ~* (mobile|nokia|iphone|ipad|android|samsung|htc|blackberry)) }
        rewrite  ^(.*) $scheme://$host/m/ permanent;
    }

    if ($http_user_agent !~* (mobile|nokia|iphone|ipad|android|samsung|htc|blackberry))}
      rewrite  ^(.*) $scheme://$host/web/ permanent;
    }
}

**Comment by Qinmei** [comment]
前台加载久先F12看看网络连接是哪个比较慢， 然后再判断什么原因；

nginx我测试应该是没问题的， 可以贴出配置文件看下
