### ISSUE TITLE
关于移动端和pc端

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#81]
更新多少话连载多少话动漫详细哪里显示多少话我自己的没有然后去你演示站也是这样

**Comment by Qinmei** [comment]
麻烦补充详细的截图

**Comment by 183452584** [comment]
弹幕，连载多少话，邮件认证，目前3个出现了bug，请确认
![Uploading -346e083b57fa53f8.jpg…]()
![Screenshot_2020-06-17-20-24-41-770_com android browser](https://user-images.githubusercontent.com/47927966/84899001-ac66d180-b0da-11ea-83b8-5479bea3ad84.jpg)
![Uploading Screenshot_2020-06-17-20-21-45-718_com.android.browser.jpg…]()

**Comment by Qinmei** [comment]
图片挂了

**Comment by 183452584** [comment]
![Uploading -346e083b57fa53f8.jpg…]()
这是连载多少话bug
![Uploading Screenshot_2020-06-17-20-24-41-770_com.android.browser.jpg…]()
邮件认证的bug
![Uploading Screenshot_2020-06-17-20-21-45-718_com.android.browser.jpg…]()
弹幕的bug

**Comment by Qinmei** [comment]
你这些图片都没有地址啊，建议以后先上传到SM.MS然后直接复制地址过来就行

**Comment by 183452584** [comment]
QQ上面发你了，你看看吧，

**Comment by Qinmei** [comment]
好， 不过以后尽量少用QQ交流， 太零碎了， 我基本上都是抽个周末时间统一解决issue上面的BUG， 这上面的信息越详细， 到时候处理起来越快

**Comment by 183452584** [comment]
对了，添加番剧时候，有连载跟完结2选择，能加入一个未开播的的选项么？一般添加新番会有用到的。

**Comment by Qinmei** [comment]
这个可以考虑

**Comment by 183452584** [comment]
点击登陆后个人信息页面也有点bug，第1头像区域不显示图片，2番剧上传也有点问题，上传番剧信息跑到漫画了，http://sadasd.hz.wanyuanyun.com/QQ%E6%88%AA%E5%9B%BE20200618213737.png

**Comment by Qinmei** [comment]
头像不显示你还是检查下自己的设置吧

**Comment by 183452584** [comment]
个人资料编程之后保存就报错了
http://sadasd.hz.wanyuanyun.com/360%E6%88%AA%E5%9B%BE20200618235501408.jpg

**Comment by 183452584** [comment]
群主那个二段定向链接视频播放不了列如这种打算丢QQ空间 http://quan.qq.com/video/1098_841c97f975eb7751dd31a08dd0090db0

**Comment by Qinmei** [comment]
这种链接暂时没办法
