### ISSUE TITLE
采集数据有问题

### ISSUE THREAD

**Issue by haig233** [Qinmei/qinvideo#82]
![image](https://user-images.githubusercontent.com/25719719/84889892-35c2d780-b0cc-11ea-95b9-529cc4dc5c17.png)
采集出来的数据，所有首播数据都是2016年
![image](https://user-images.githubusercontent.com/25719719/84890005-5f7bfe80-b0cc-11ea-89a6-ab2bbb7c7a0f.png)
资源站这边的数据又是正确的

**Comment by Qinmei** [comment]
唔，这是默认日期，应该是没有正确采集到年份

**Comment by Qinmei** [comment]
把采集地址发下，我看看格式

**Comment by haig233** [comment]
> 把采集地址发下，我看看格式

https://cj.okzy.tv/inc/apickm3u8s_subname.php
