### ISSUE TITLE
1个问题，2个建议

### ISSUE THREAD

**Issue by miccan** [Qinmei/qinvideo#83]
问题：
1.search点击后为空白。
建议：
1.现DPlayer能够查看视频的链接，这样开启不开启下载功能都一样，建议隐藏地址。
2.模板建议增加影片或短视频。（个人认为这个通用性比剧集强）

**Comment by Qinmei** [comment]
提BUG请附上完整的截图， 这样才能去定位问题；

建议：
1.什么播放器都不能隐藏地址，因为你调用的就是浏览器HTML5接口，除非你用flash去播放；

2.影片跟短视频就是一个类型而已，加起来很快， 但是现阶段没有这个时间精力去弄；后续等有空了再去拓展吧
