### ISSUE TITLE
2.21版本新bug

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#85]
2.2.1新版本无法注册，出现了bug
![Screenshot_2020-06-30-15-01-22-617_com android browser](https://user-images.githubusercontent.com/47927966/86094257-dc52a380-bae2-11ea-938a-7008f314688a.jpg)

**Comment by Qinmei** [comment]
这次改动不涉及注册相关的东西，周末再看下

**Comment by 183452584** [comment]
点注册时候没反应

**Comment by 183452584** [comment]
![Screenshot_2020-07-11-03-22-24-734_com rdc_zh android](https://user-images.githubusercontent.com/47927966/87190965-1105fc80-c326-11ea-90bb-403bba2ce1de.jpg)
测试了一下用户编辑资料无法保存

**Comment by 183452584** [comment]
还有专栏分季可以添加一个排列么？感觉好乱

**Comment by Qinmei** [comment]
分季这个暂时解决不了
