### ISSUE TITLE
新版本bug

### ISSUE THREAD

**Issue by 183452584** [Qinmei/qinvideo#86]
![Screenshot_2020-07-12-07-41-05-045_com tencent mobileqq](https://user-images.githubusercontent.com/47927966/87235863-af23c080-c413-11ea-9af4-3810b0dd9489.png)
目前出现2问题1轮播图没了，2点击点首页新番专栏那些出空白要刷新出才看的到，以上都是移动端的问题，有空看看吧
![Screenshot_2020-07-12-07-41-10-920_com tencent mobileqq](https://user-images.githubusercontent.com/47927966/87235864-b1861a80-c413-11ea-90f0-da028e959378.png)

**Comment by Qinmei** [comment]
重新设置保存下
