### ISSUE TITLE
关于Dplayer加载慢的问题

### ISSUE THREAD

**Issue by 26e1** [Qinmei/qinvideo#9]
是否可以加入p2p加速，测试了很多次，原生deplayer不仅开始载入视频要很久，播放中跨越进度条也需要缓冲很久。同视频源别的框架就很快。并且视频越大需要的时间越多。对于一个视频网站来说这个真的很硬伤...

**Comment by Qinmei** [comment]
Dplayer本身是没有p2p功能的, 如果你有相关的源码, 我可以研究下, 另外尽量不要用MP4格式, 这玩意没法快的

**Comment by 26e1** [comment]
https://github.com/cdnbye/P2P-DPlayer

**Comment by Qinmei** [comment]
cdnbye是付费项目, 暂时不会引用进来

**Comment by 26e1** [comment]
好吧，顺便想请问下这个使用解析是播放类型选解析然后勾选使用前缀在前缀填上解析接口吗
