### ISSUE TITLE
打开首页报错，提示Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by BisonReto** [Qinmei/qinvideo#90]
![image](https://user-images.githubusercontent.com/14340149/87839726-b729a780-c8ce-11ea-8a9e-8cf8dea953b4.png)

在新建几个视频后，然后刷新首页就报错，出现上面的错误，不太清楚为何出错，即使尝试在public/web/下停止删除然后重启也不行，把_next目录给删除，重新编译，也是报同样错误，看错误提示，/node/qinVideo/public/web/_next/static/chunks/framework.619a4f70c1d4d3a29cbc.js还有/node/qinVideo/public/web/_next/static/mu-xQWWF0d1dxCs2fi3lb/pages/index.js出现错误，请问大佬能帮忙看一下是什么出错？有什么方式解决一下？

**Comment by Qinmei** [comment]
先别开启服务端渲染, 这块可能有点问题, 暂时没时间去解决了

**Comment by BisonReto** [comment]
好的，直接访问是吧

**Comment by BisonReto** [comment]
![image](https://user-images.githubusercontent.com/14340149/87843763-a6d2f600-c8e9-11ea-9149-cb4932026f92.png)
不过我采用直连采用进入首页就会这样，是空白，为啥，需要配置啥？

**Comment by BisonReto** [comment]
没事了，谢谢，是我配置的问题

**Comment by EasyDuan** [comment]
> 没事了，谢谢，是我配置的问题

怎么处理的配置问题？我也遇到了同样问题，谢谢

**Comment by EasyDuan** [comment]
请问问题怎么解决的，谢谢
