### ISSUE TITLE
【功能建议】关于文本编辑器和要饭二维码的问题与建议

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#91]
我最初的目的是想在文章页面放一个要饭二维码，但是上传图片后是全屏显示图片。效果如下图：
![image](https://user-images.githubusercontent.com/9511835/88006303-e5f98500-cb3d-11ea-87c1-711591d65e3a.png)

我想将图片进行缩放并居中显示，看见qinvideo文档里写支持Markdown。
![image](https://user-images.githubusercontent.com/9511835/88006468-47215880-cb3e-11ea-9ca8-d823a7aa6883.png)

尝试了一下用Markdown引用图片，但Markdown语法无法完成解析。效果如下图：
![image](https://user-images.githubusercontent.com/9511835/88006563-818af580-cb3e-11ea-958b-aa6b15dc0847.png)

然后我简单的研究了一下这个编辑器，发现好像是Quill editor，网上的方法说可以通过模块来实现图片的拖拽和缩放。
参考：https://www.cnblogs.com/zr123/p/12206031.html

之前使用的Typecho编辑器可以通过 '!!!' '!!!' 方式嵌入html代码，希望也可以参考这种方式来扩展文本编辑。
参考：https://www.wusiqi.cn/archives/391/

其实最初的想法就是想放一个要饭二维码，如果作者大大能够在视频页和文章页提供赞助接口就再好不过了（通常只需要微信和支付宝的二维码就够了）。
参考：https://github.com/greedying/tctip

赞助按钮的参考位置：
PC端视频页
![image](https://user-images.githubusercontent.com/9511835/88008949-f0b71880-cb43-11ea-9ef8-9523fcf08a7c.png)
PC端文章页
![image](https://user-images.githubusercontent.com/9511835/88009048-2956f200-cb44-11ea-9630-854a78814683.png)
移动端视频页(手机上显示样式目前还有些bug，测试手机是iPhone 6sp，建议两排显示，问题反馈和赞助放到第二排）
![image](https://user-images.githubusercontent.com/9511835/88009278-b39f5600-cb44-11ea-832f-9897641f04d5.png)
移动端文章页
![image](https://user-images.githubusercontent.com/9511835/88009342-ddf11380-cb44-11ea-816a-0e57e7063c8a.png)

以上为我对编辑器和要饭二维码的建议。

**Comment by Qinmei** [comment]
文章编辑器功能一般般，基本上是目前的最优解了，原生的markdow语法按理说是支持的，具体的后续再研究研究， 主要是考虑到到时候要做前端用户投稿，所以不能直接支持那些html啥的， 这个没啥太好的方法；

赞赏接口这个怎么说呢， APP其实是可以直接点击唤起支付宝然后跳转到转账的页面，  也就是捐赠这个， 很多独立APP用的比较多， 现在不知道有没有限制， 我本来是打算直接在APP提供的， 也就是说取消移动页面大力推APP， 考虑到有一些苹果用户可能无法安装， 所以也是有点艰难；

另外移动端的基本上给了二维码也扫不了， 最好的就是弄个收款接口， 也就是那种卖卡的， 点击直接跳转去支付就是了， 或者引流到微信公众号， 然后让用户打赏， 也是比较现实的方案

目前很多计划都搁置了，我要投入全部精力去准备工作上的事， 像播放器以及APP还有主题等等这些都是计划要调整， 估计最理想的情况就是明年去大改了， 现在都做不了啥。。。。

**Comment by Tridagger** [comment]
好的！理解！祝愿工作顺利！
