### ISSUE TITLE
部分缩略图的默认值建议由竖向图改成横向图

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#93]
发布资源时分别上传了横向图和竖向图
![image](https://user-images.githubusercontent.com/9511835/90611551-7b6d5f00-e239-11ea-9fda-f52879b25ab3.png)
在这两个地方建议将默认图改成横向图，目前是竖向图，显示不全。
![image](https://user-images.githubusercontent.com/9511835/90611668-9c35b480-e239-11ea-8144-d148faa10304.png)
![image](https://user-images.githubusercontent.com/9511835/90611695-a48def80-e239-11ea-8a3a-8a662bf47d12.png)

**Comment by Qinmei** [comment]
这两个地方本来是给剧集缩略图留的， 目前就是简单弄弄
