### ISSUE TITLE
【BUG】用户页背景图和头像都不显示

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#94]
如图所示  域名/user  
![image](https://user-images.githubusercontent.com/9511835/90983073-0a61da80-e59e-11ea-8cb7-b81bef19cc4f.png)

查看元素，图片的url都为qinmei.video的链接。
![image](https://user-images.githubusercontent.com/9511835/90983104-3aa97900-e59e-11ea-810a-a58a5838eb1a.png)

但从文章处点击头像  进入  域名/user/后缀   显示正常
![image](https://user-images.githubusercontent.com/9511835/90983168-ab509580-e59e-11ea-9ac5-898ab0e8e4f6.png)

**Comment by Tridagger** [comment]
因为用户页不显示图片，我发现图片文件夹有好多用户上传的冗余的头像和背景图。

**Comment by Qinmei** [comment]
首次进入显示的可能是默认图片， 也就是说用户信息没有加载出来， 这块可能要调整下

图片文件夹都是用户上传的图片， 当然也可能是默认自带的图片， 这个到时候可能要写个脚本去跑一下， 把一些过期不用的图片都清理掉
