### ISSUE TITLE
目前有没有强制刷新缓存的方法呢

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#95]
在后台修改文章，或者做一些设置更改时，无法即时的看到变化，有没有什么强制刷新缓存的命令呢？或者也可以在后台加入这一功能。

**Comment by Tridagger** [comment]
目前文章好像无法删除。

**Comment by Tridagger** [comment]
我把要删的文章改个名，改个内容，临时能够应对。再提一个建议，现在搜索功能，只能搜索到文章名称，不能搜索文章内容，希望可以改进一下。

**Comment by Qinmei** [comment]
直接在redis那设置就行， 清空所有缓存就OK

**Comment by Qinmei** [comment]
文章删除有点问题, 可以使用批量删除
