### ISSUE TITLE
【BUG】无法发送评论

### ISSUE THREAD

**Issue by Tridagger** [Qinmei/qinvideo#97]
更新到2.2.3时发现，已验证的账号无法发送评论，貌似之前的版本也有这个问题，我当时没有注意。注册人数越来越多，评论一个没有，我才意识到测试一下。

提示信息
![image](https://user-images.githubusercontent.com/9511835/91673051-a2def880-eb64-11ea-9b68-fbb48d8ca7e1.png)
![image](https://user-images.githubusercontent.com/9511835/91673068-ba1de600-eb64-11ea-80de-325a0620e308.png)

**Comment by Qinmei** [comment]
嗯， 简单看了下， 应该是后续新增敏感词校验的时候导致的错误， 晚上修复下
