### ISSUE TITLE
无法运行，报错如下怎么解决？

### ISSUE THREAD

**Issue by nettimes** [Qinmei/qinvideo#99]
`[root@ecs-bijqO qin]# npm start --ignore-stderr

> qinvideo-node@1.0.0 start /node/qin
> egg-scripts start --daemon --title=egg-server-qinvideo-node

[egg-scripts] Starting egg application at /node/qin
[egg-scripts] Run node --require /node/qin/node_modules/source-map-support/register.js /node/qin/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-qinvideo-node","baseDir":"/node/qin","framework":"/node/qin/node_modules/egg"} --title=egg-server-qinvideo-node
[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] Wait Start: 6...
[egg-scripts] Wait Start: 7...
[egg-scripts] Wait Start: 8...
[egg-scripts] Wait Start: 9...
[egg-scripts] Wait Start: 10...
[egg-scripts] Wait Start: 11...
[egg-scripts] Wait Start: 12...
[egg-scripts] Wait Start: 13...
[egg-scripts] Wait Start: 14...
[egg-scripts] tail -n 100 /root/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] (node:26113) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
[egg-scripts] (node:26105) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
[egg-scripts] (node:26113) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
[egg-scripts] (node:26105) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
[egg-scripts] (node:26119) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
[egg-scripts] 
[egg-scripts] Start got error, see /root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qinvideo-node@1.0.0 start: `egg-scripts start --daemon --title=egg-server-qinvideo-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qinvideo-node@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-22T15_27_43_804Z-debug.log`

**Comment by Qinmei** [comment]
数据库连接不上， 仔细检查下数据库的配置

**Comment by freeimg** [comment]
数据库是支持的配置

**Comment by Qinmei** [comment]
yarn dev 能启动？

那就 yarn start --ignore-stderr  再试下

**Comment by freeimg** [comment]
npm run dev没问题
但是使用 npm start --ignore-stderr 报错就是上面的信息

**Comment by Qinmei** [comment]
多试几次，不行的话将npm换成yarn， 具体的可以百度下
